### ISSUE TITLE
phpro/zf-doctrine-hydration-module EOL

### ISSUE THREAD

**Issue by TomHAnderson** [laminas-api-tools/api-tools-doctrine#15]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

This repository requires:
```
"phpro/zf-doctrine-hydration-module": "^2.0.1 || ^3.0 || ^4.1"
```

I received this email from the owner of that repository today:
```
Hello @TomHAnderson

We are no longer using Apigility at PHPro anymore.
Therefor, it is hard for me to make the correct decisions for this package.

Feel free to use this package as a base for a new laminas package. Once that one is ready, we can archive this one.

Let me know if there is something I can do to make it easier to hand over the project.
```
Laminas API Tools could take over maintenance of the package.  If Laminas does not want this responsibility I'll gladly move it to API Skeletons.

RSVP

**Comment by weierophinney** [comment]
Pinging @michalbundyra ...

**Comment by michalbundyra** [comment]
@TomHAnderson Thanks for the info. We'd like to include it into Laminas, or move just part of it, what is used by our components. It is not anything urgent right now, as integration works through the bridge library.

Definitely we will be back to this at some point. Thanks.

**Comment by javabudd** [comment]
@michalbundyra Any updates on this? I'd be happy to help if any is needed.

**Comment by BacLuc** [comment]
+1 
this dependency blocks our update of doctrine/doctrine-orm-module.
anything i can do to help?
https://github.com/ecamp/ecamp3/pull/761

**Comment by TomHAnderson** [comment]
Just yesterday I rewrote the Phpro library.  I was able to make it work for my needs but I removed the ODM portion.   I got rather far in the ODM unit tests but hit a point where I got stuck and, since I haven't seen anyone paying attention to this repository, I just went my own way.

I would be happy to reproduce my work with the caveat that I'll need help with the ODM unit tests.  But before that can happen a decision needs to be made about what will become of the Phpro library.  

I strongly recommend the Phpro library be brought under the Laminas umbrella so this library does not rely on the external dependency.  Once the library exists as part of api-tools I'll submit PRs for the work I can do.

I also rewrote this library yesterday to use the rewritten Phpro library.  That was not difficult with just some changes for Doctrine persistence.

https://github.com/API-Skeletons/doctrine-orm-hydration-module
https://github.com/API-Skeletons/api-tools-doctrine

To be honest my expectations of anything changing to make this repository function again are very low.  Please prove me wrong.

**Comment by BacLuc** [comment]
> Just yesterday I rewrote the Phpro library. I was able to make it work for my needs but I removed the ODM portion. I got rather far in the ODM unit tests but hit a point where I got stuck and, since I haven't seen anyone paying attention to this repository, I just went my own way.
> 
> I would be happy to reproduce my work with the caveat that I'll need help with the ODM unit tests. But before that can happen a decision needs to be made about what will become of the Phpro library.
> 
> I strongly recommend the Phpro library be brought under the Laminas umbrella so this library does not rely on the external dependency. Once the library exists as part of api-tools I'll submit PRs for the work I can do.
> 
> I also rewrote this library yesterday to use the rewritten Phpro library. That was not difficult with just some changes for Doctrine persistence.
> 
> https://github.com/API-Skeletons/doctrine-orm-hydration-module
> https://github.com/API-Skeletons/api-tools-doctrine
> 
> To be honest my expectations of anything changing to make this repository function again are very low. Please prove me wrong.

What can be done to advance the solution of this issue?
Who decides if this library is brought under the Laminas umbrella?
Would it help if someone sponsors the migration and update of phpro/zf-doctrine-hydration-module?

**Comment by javabudd** [comment]
Is something like https://github.com/API-Skeletons/doctrine-orm-hydration-module viable or will this be brought under the Laminas project?

**Comment by TomHAnderson** [comment]
https://github.com/doctrine/doctrine-laminas-hydrator is my recommended library to replace phpro.  This library is maintained and up to date.

**Comment by javabudd** [comment]
Thanks @TomHAnderson, I think this issue can be closed out then. I'm working on getting a PR to replace phpro.
