### ISSUE TITLE
Builds failing with composer plugin error

### ISSUE THREAD

**Issue by javabudd** [laminas-api-tools/api-tools-doctrine#32]
### Bug Report

| Version(s)  | 2.5.x

#### Summary
Builds against the 2.5.x branch (and possibly others) are failing due to a composer 2 security setting regarding allowable plugins. [Example](https://github.com/laminas-api-tools/api-tools-doctrine/actions/runs/3348763883/jobs/5548718412) of a failed build that had no code changes and still failed. This could be happening on many Laminas libraries as it seems like it stems from [laminas-ci-matrix-action](https://github.com/laminas/laminas-ci-matrix-action).

#### Current behavior
All Github Actions builds are failing on the 2.5.x branch.

#### How to reproduce
Create a pull request into the 2.5.x branch to trigger a build.

#### Expected behavior
Builds should pass assuming no code changes have been made.

**Comment by Ocramius** [comment]
Seems to just be an issue with very old `composer.json`, while `composer/composer:^2.3` onwards broke BC by introducing required config for any plugins to be run.

This section needs adjustment:

https://github.com/laminas-api-tools/api-tools-doctrine/blob/675e8eed316b2d35d76688ed1ed1ba8bda8f1fea/composer.json#L20-L22

Here's an example of how plugins are configured in `laminas/laminas-servicemanager`:

https://github.com/laminas/laminas-servicemanager/blob/166c5687ac2f48790fed854387327da28afbf088/composer.json#L23-L33

**Comment by javabudd** [comment]
Good find, I'll submit a PR to fix.

**Comment by javabudd** [comment]
new PR that addresses the issue:

https://github.com/laminas-api-tools/api-tools-doctrine/pull/35
